# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BotPackPartial(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'icon': 'str',
        'banner': 'str',
        'bots': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'icon': 'icon',
        'banner': 'banner',
        'bots': 'bots'
    }

    def __init__(self, name=None, description=None, icon=None, banner=None, bots=None):  # noqa: E501
        """BotPackPartial - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._icon = None
        self._banner = None
        self._bots = None
        self.discriminator = None
        self.name = name
        self.description = description
        if icon is not None:
            self.icon = icon
        if banner is not None:
            self.banner = banner
        self.bots = bots

    @property
    def name(self):
        """Gets the name of this BotPackPartial.  # noqa: E501


        :return: The name of this BotPackPartial.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BotPackPartial.


        :param name: The name of this BotPackPartial.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this BotPackPartial.  # noqa: E501


        :return: The description of this BotPackPartial.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BotPackPartial.


        :param description: The description of this BotPackPartial.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def icon(self):
        """Gets the icon of this BotPackPartial.  # noqa: E501


        :return: The icon of this BotPackPartial.  # noqa: E501
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this BotPackPartial.


        :param icon: The icon of this BotPackPartial.  # noqa: E501
        :type: str
        """

        self._icon = icon

    @property
    def banner(self):
        """Gets the banner of this BotPackPartial.  # noqa: E501


        :return: The banner of this BotPackPartial.  # noqa: E501
        :rtype: str
        """
        return self._banner

    @banner.setter
    def banner(self, banner):
        """Sets the banner of this BotPackPartial.


        :param banner: The banner of this BotPackPartial.  # noqa: E501
        :type: str
        """

        self._banner = banner

    @property
    def bots(self):
        """Gets the bots of this BotPackPartial.  # noqa: E501


        :return: The bots of this BotPackPartial.  # noqa: E501
        :rtype: list[str]
        """
        return self._bots

    @bots.setter
    def bots(self, bots):
        """Sets the bots of this BotPackPartial.


        :param bots: The bots of this BotPackPartial.  # noqa: E501
        :type: list[str]
        """
        if bots is None:
            raise ValueError("Invalid value for `bots`, must not be `None`")  # noqa: E501

        self._bots = bots

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BotPackPartial, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BotPackPartial):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
