# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BotPromotion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'info': 'str',
        'css': 'str',
        'type': 'PromotionType'
    }

    attribute_map = {
        'title': 'title',
        'info': 'info',
        'css': 'css',
        'type': 'type'
    }

    def __init__(self, title=None, info=None, css=None, type=None):  # noqa: E501
        """BotPromotion - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._info = None
        self._css = None
        self._type = None
        self.discriminator = None
        self.title = title
        self.info = info
        if css is not None:
            self.css = css
        self.type = type

    @property
    def title(self):
        """Gets the title of this BotPromotion.  # noqa: E501


        :return: The title of this BotPromotion.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BotPromotion.


        :param title: The title of this BotPromotion.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def info(self):
        """Gets the info of this BotPromotion.  # noqa: E501


        :return: The info of this BotPromotion.  # noqa: E501
        :rtype: str
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this BotPromotion.


        :param info: The info of this BotPromotion.  # noqa: E501
        :type: str
        """
        if info is None:
            raise ValueError("Invalid value for `info`, must not be `None`")  # noqa: E501

        self._info = info

    @property
    def css(self):
        """Gets the css of this BotPromotion.  # noqa: E501


        :return: The css of this BotPromotion.  # noqa: E501
        :rtype: str
        """
        return self._css

    @css.setter
    def css(self, css):
        """Sets the css of this BotPromotion.


        :param css: The css of this BotPromotion.  # noqa: E501
        :type: str
        """

        self._css = css

    @property
    def type(self):
        """Gets the type of this BotPromotion.  # noqa: E501


        :return: The type of this BotPromotion.  # noqa: E501
        :rtype: PromotionType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BotPromotion.


        :param type: The type of this BotPromotion.  # noqa: E501
        :type: PromotionType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BotPromotion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BotPromotion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
