# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class APIV2PromotionsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_promotion(self, bot_id, id, **kwargs):  # noqa: E501
        """Delete Promotion  # noqa: E501

        Deletes a bots promotion  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_promotion(bot_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int bot_id: (required)
        :param str id: (required)
        :return: APIResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_promotion_with_http_info(bot_id, id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_promotion_with_http_info(bot_id, id, **kwargs)  # noqa: E501
            return data

    def delete_promotion_with_http_info(self, bot_id, id, **kwargs):  # noqa: E501
        """Delete Promotion  # noqa: E501

        Deletes a bots promotion  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_promotion_with_http_info(bot_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int bot_id: (required)
        :param str id: (required)
        :return: APIResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['bot_id', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_promotion" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'bot_id' is set
        if ('bot_id' not in params or
                params['bot_id'] is None):
            raise ValueError("Missing the required parameter `bot_id` when calling `delete_promotion`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `delete_promotion`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bot_id' in params:
            path_params['bot_id'] = params['bot_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bot']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/bots/{bot_id}/promotions/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='APIResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def edit_promotion(self, body, bot_id, id, **kwargs):  # noqa: E501
        """Edit Promotion  # noqa: E501

        Edits an promotion for a bot given its promotion ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.edit_promotion(body, bot_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BotPromotion body: (required)
        :param int bot_id: (required)
        :param str id: (required)
        :return: APIResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.edit_promotion_with_http_info(body, bot_id, id, **kwargs)  # noqa: E501
        else:
            (data) = self.edit_promotion_with_http_info(body, bot_id, id, **kwargs)  # noqa: E501
            return data

    def edit_promotion_with_http_info(self, body, bot_id, id, **kwargs):  # noqa: E501
        """Edit Promotion  # noqa: E501

        Edits an promotion for a bot given its promotion ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.edit_promotion_with_http_info(body, bot_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BotPromotion body: (required)
        :param int bot_id: (required)
        :param str id: (required)
        :return: APIResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'bot_id', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method edit_promotion" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `edit_promotion`")  # noqa: E501
        # verify the required parameter 'bot_id' is set
        if ('bot_id' not in params or
                params['bot_id'] is None):
            raise ValueError("Missing the required parameter `bot_id` when calling `edit_promotion`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `edit_promotion`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bot_id' in params:
            path_params['bot_id'] = params['bot_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bot']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/bots/{bot_id}/promotions/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='APIResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_promotion(self, bot_id, **kwargs):  # noqa: E501
        """Get Promotion  # noqa: E501

        Returns all the promotions for a bot on Fates List  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_promotion(bot_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int bot_id: (required)
        :return: BotPromotions
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_promotion_with_http_info(bot_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_promotion_with_http_info(bot_id, **kwargs)  # noqa: E501
            return data

    def get_promotion_with_http_info(self, bot_id, **kwargs):  # noqa: E501
        """Get Promotion  # noqa: E501

        Returns all the promotions for a bot on Fates List  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_promotion_with_http_info(bot_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int bot_id: (required)
        :return: BotPromotions
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['bot_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_promotion" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'bot_id' is set
        if ('bot_id' not in params or
                params['bot_id'] is None):
            raise ValueError("Missing the required parameter `bot_id` when calling `get_promotion`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bot_id' in params:
            path_params['bot_id'] = params['bot_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/bots/{bot_id}/promotions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BotPromotions',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def new_promotion(self, body, bot_id, **kwargs):  # noqa: E501
        """New Promotion  # noqa: E501

        Creates a promotion for a bot. Type can be 1 for announcement, 2 for promotion or 3 for generic  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.new_promotion(body, bot_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BotPromotion body: (required)
        :param int bot_id: (required)
        :return: APIResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.new_promotion_with_http_info(body, bot_id, **kwargs)  # noqa: E501
        else:
            (data) = self.new_promotion_with_http_info(body, bot_id, **kwargs)  # noqa: E501
            return data

    def new_promotion_with_http_info(self, body, bot_id, **kwargs):  # noqa: E501
        """New Promotion  # noqa: E501

        Creates a promotion for a bot. Type can be 1 for announcement, 2 for promotion or 3 for generic  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.new_promotion_with_http_info(body, bot_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BotPromotion body: (required)
        :param int bot_id: (required)
        :return: APIResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'bot_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method new_promotion" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `new_promotion`")  # noqa: E501
        # verify the required parameter 'bot_id' is set
        if ('bot_id' not in params or
                params['bot_id'] is None):
            raise ValueError("Missing the required parameter `bot_id` when calling `new_promotion`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'bot_id' in params:
            path_params['bot_id'] = params['bot_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bot']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/bots/{bot_id}/promotions', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='APIResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
