# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_pack_bot_status import AllOfPackBotStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfPackBotStatus(unittest.TestCase):
    """AllOfPackBotStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfPackBotStatus(self):
        """Test AllOfPackBotStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_pack_bot_status.AllOfPackBotStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
