# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_v2___servers_api import APIV2ServersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIV2ServersApi(unittest.TestCase):
    """APIV2ServersApi unit test stubs"""

    def setUp(self):
        self.api = APIV2ServersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_random_server(self):
        """Test case for fetch_random_server

        Fetch Random Server  # noqa: E501
        """
        pass

    def test_fetch_server(self):
        """Test case for fetch_server

        Fetch Server  # noqa: E501
        """
        pass

    def test_get_server_invite(self):
        """Test case for get_server_invite

        Get Server Invite  # noqa: E501
        """
        pass

    def test_get_server_page(self):
        """Test case for get_server_page

        Get Server Page  # noqa: E501
        """
        pass

    def test_get_server_widget(self):
        """Test case for get_server_widget

        Server Widget  # noqa: E501
        """
        pass

    def test_get_server_ws_events(self):
        """Test case for get_server_ws_events

        Get Server Ws Events  # noqa: E501
        """
        pass

    def test_regenerate_server_token(self):
        """Test case for regenerate_server_token

        Regenerate Server Token  # noqa: E501
        """
        pass

    def test_server_exists(self):
        """Test case for server_exists

        Server Exists  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
