# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_v2___users_api import APIV2UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIV2UsersApi(unittest.TestCase):
    """APIV2UsersApi unit test stubs"""

    def setUp(self):
        self.api = APIV2UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_bot(self):
        """Test case for add_bot

        Add Bot  # noqa: E501
        """
        pass

    def test_appeal_bot(self):
        """Test case for appeal_bot

        Appeal Bot  # noqa: E501
        """
        pass

    def test_bot_backup(self):
        """Test case for bot_backup

        Bot Backup  # noqa: E501
        """
        pass

    def test_certify_bot_request(self):
        """Test case for certify_bot_request

        Certify Bot Request  # noqa: E501
        """
        pass

    def test_create_bot_pack(self):
        """Test case for create_bot_pack

        Create Bot Pack  # noqa: E501
        """
        pass

    def test_delete_bot(self):
        """Test case for delete_bot

        Delete Bot  # noqa: E501
        """
        pass

    def test_delete_bot_pack(self):
        """Test case for delete_bot_pack

        Delete Bot Pack  # noqa: E501
        """
        pass

    def test_edit_bot(self):
        """Test case for edit_bot

        Edit Bot  # noqa: E501
        """
        pass

    def test_fetch_user(self):
        """Test case for fetch_user

        Fetch User  # noqa: E501
        """
        pass

    def test_get_cache_user(self):
        """Test case for get_cache_user

        Get Cache User  # noqa: E501
        """
        pass

    def test_get_user_votes(self):
        """Test case for get_user_votes

        Get User Votes  # noqa: E501
        """
        pass

    def test_regenerate_user_token(self):
        """Test case for regenerate_user_token

        Regenerate User Token  # noqa: E501
        """
        pass

    def test_transfer_bot_ownership(self):
        """Test case for transfer_bot_ownership

        Transfer Bot Ownership  # noqa: E501
        """
        pass

    def test_update_bot_pack(self):
        """Test case for update_bot_pack

        Update Bot Pack  # noqa: E501
        """
        pass

    def test_update_user_preferences(self):
        """Test case for update_user_preferences

        Update User Preferences  # noqa: E501
        """
        pass

    def test_update_vote_reminders(self):
        """Test case for update_vote_reminders

        Update Vote Reminders  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
