# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_v2___policies_api import APIV2PoliciesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIV2PoliciesApi(unittest.TestCase):
    """APIV2PoliciesApi unit test stubs"""

    def setUp(self):
        self.api = APIV2PoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_policies(self):
        """Test case for all_policies

        All Policies  # noqa: E501
        """
        pass

    def test_privacy_policy(self):
        """Test case for privacy_policy

        Privacy Policy  # noqa: E501
        """
        pass

    def test_rules(self):
        """Test case for rules

        Rules  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
