# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_v2___auth_api import APIV2AuthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIV2AuthApi(unittest.TestCase):
    """APIV2AuthApi unit test stubs"""

    def setUp(self):
        self.api = APIV2AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_login_link(self):
        """Test case for get_login_link

        Get Login Link  # noqa: E501
        """
        pass

    def test_login_user(self):
        """Test case for login_user

        Login User  # noqa: E501
        """
        pass

    def test_logout_sunbeam(self):
        """Test case for logout_sunbeam

        Logout Sunbeam  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
