# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_v2___reviews_api import APIV2ReviewsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIV2ReviewsApi(unittest.TestCase):
    """APIV2ReviewsApi unit test stubs"""

    def setUp(self):
        self.api = APIV2ReviewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_review(self):
        """Test case for delete_review

        Delete Review  # noqa: E501
        """
        pass

    def test_edit_review(self):
        """Test case for edit_review

        Edit Review  # noqa: E501
        """
        pass

    def test_get_all_reviews(self):
        """Test case for get_all_reviews

        Get All Reviews  # noqa: E501
        """
        pass

    def test_new_review(self):
        """Test case for new_review

        New Review  # noqa: E501
        """
        pass

    def test_vote_review_api(self):
        """Test case for vote_review_api

        Vote Review Api  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
