# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_v2___system_api import APIV2SystemApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIV2SystemApi(unittest.TestCase):
    """APIV2SystemApi unit test stubs"""

    def setUp(self):
        self.api = APIV2SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_bot_info(self):
        """Test case for add_bot_info

        Add Bot Info  # noqa: E501
        """
        pass

    def test_check_staff_member(self):
        """Test case for check_staff_member

        Check Staff Member  # noqa: E501
        """
        pass

    def test_csp_report(self):
        """Test case for csp_report

        Csp Report  # noqa: E501
        """
        pass

    def test_get_all_vote_reminders(self):
        """Test case for get_all_vote_reminders

        Get All Vote Reminders  # noqa: E501
        """
        pass

    def test_get_botlist_stats(self):
        """Test case for get_botlist_stats

        Get Botlist Stats  # noqa: E501
        """
        pass

    def test_get_bots_filtered(self):
        """Test case for get_bots_filtered

        Get Bots Filtered  # noqa: E501
        """
        pass

    def test_get_index(self):
        """Test case for get_index

        Get Index  # noqa: E501
        """
        pass

    def test_get_partners(self):
        """Test case for get_partners

        Get Partners  # noqa: E501
        """
        pass

    def test_get_staff_roles(self):
        """Test case for get_staff_roles

        Get Staff Roles  # noqa: E501
        """
        pass

    def test_get_top_spots(self):
        """Test case for get_top_spots

        Get Top Spots  # noqa: E501
        """
        pass

    def test_get_vanity(self):
        """Test case for get_vanity

        Get Vanity  # noqa: E501
        """
        pass

    def test_search_by_tag(self):
        """Test case for search_by_tag

        Search By Tag  # noqa: E501
        """
        pass

    def test_search_list(self):
        """Test case for search_list

        Search List  # noqa: E501
        """
        pass

    def test_sellix_webhook(self):
        """Test case for sellix_webhook

        Sellix Webhook  # noqa: E501
        """
        pass

    def test_stats_page(self):
        """Test case for stats_page

        Stats Page  # noqa: E501
        """
        pass

    def test_troubleshoot_api(self):
        """Test case for troubleshoot_api

        Troubleshoot Api  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
