# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_v2___custom_resources_api import APIV2CustomResourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIV2CustomResourcesApi(unittest.TestCase):
    """APIV2CustomResourcesApi unit test stubs"""

    def setUp(self):
        self.api = APIV2CustomResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_resources(self):
        """Test case for add_resources

        Add Resources  # noqa: E501
        """
        pass

    def test_delete_resources(self):
        """Test case for delete_resources

        Delete Resources  # noqa: E501
        """
        pass

    def test_get_resources(self):
        """Test case for get_resources

        Get Resources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
