# coding: utf-8

"""
    Fates List

                 Current API: v2 beta 3             Default API: v2             API URL: https://api.fateslist.xyz             API Docs: https://apidocs.fateslist.xyz             Enum Reference: https://apidocs.fateslist.xyz/structures/enums.autogen           # noqa: E501

    OpenAPI spec version: 0.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BotIndex(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tags_fixed': 'FLTags',
        'top_voted': 'BotPartialList',
        'certified_bots': 'BotPartialList',
        'new_bots': 'BotPartialList',
        'features': 'BotFeatures'
    }

    attribute_map = {
        'tags_fixed': 'tags_fixed',
        'top_voted': 'top_voted',
        'certified_bots': 'certified_bots',
        'new_bots': 'new_bots',
        'features': 'features'
    }

    def __init__(self, tags_fixed=None, top_voted=None, certified_bots=None, new_bots=None, features=None):  # noqa: E501
        """BotIndex - a model defined in Swagger"""  # noqa: E501
        self._tags_fixed = None
        self._top_voted = None
        self._certified_bots = None
        self._new_bots = None
        self._features = None
        self.discriminator = None
        self.tags_fixed = tags_fixed
        self.top_voted = top_voted
        self.certified_bots = certified_bots
        self.new_bots = new_bots
        if features is not None:
            self.features = features

    @property
    def tags_fixed(self):
        """Gets the tags_fixed of this BotIndex.  # noqa: E501


        :return: The tags_fixed of this BotIndex.  # noqa: E501
        :rtype: FLTags
        """
        return self._tags_fixed

    @tags_fixed.setter
    def tags_fixed(self, tags_fixed):
        """Sets the tags_fixed of this BotIndex.


        :param tags_fixed: The tags_fixed of this BotIndex.  # noqa: E501
        :type: FLTags
        """
        if tags_fixed is None:
            raise ValueError("Invalid value for `tags_fixed`, must not be `None`")  # noqa: E501

        self._tags_fixed = tags_fixed

    @property
    def top_voted(self):
        """Gets the top_voted of this BotIndex.  # noqa: E501


        :return: The top_voted of this BotIndex.  # noqa: E501
        :rtype: BotPartialList
        """
        return self._top_voted

    @top_voted.setter
    def top_voted(self, top_voted):
        """Sets the top_voted of this BotIndex.


        :param top_voted: The top_voted of this BotIndex.  # noqa: E501
        :type: BotPartialList
        """
        if top_voted is None:
            raise ValueError("Invalid value for `top_voted`, must not be `None`")  # noqa: E501

        self._top_voted = top_voted

    @property
    def certified_bots(self):
        """Gets the certified_bots of this BotIndex.  # noqa: E501


        :return: The certified_bots of this BotIndex.  # noqa: E501
        :rtype: BotPartialList
        """
        return self._certified_bots

    @certified_bots.setter
    def certified_bots(self, certified_bots):
        """Sets the certified_bots of this BotIndex.


        :param certified_bots: The certified_bots of this BotIndex.  # noqa: E501
        :type: BotPartialList
        """
        if certified_bots is None:
            raise ValueError("Invalid value for `certified_bots`, must not be `None`")  # noqa: E501

        self._certified_bots = certified_bots

    @property
    def new_bots(self):
        """Gets the new_bots of this BotIndex.  # noqa: E501


        :return: The new_bots of this BotIndex.  # noqa: E501
        :rtype: BotPartialList
        """
        return self._new_bots

    @new_bots.setter
    def new_bots(self, new_bots):
        """Sets the new_bots of this BotIndex.


        :param new_bots: The new_bots of this BotIndex.  # noqa: E501
        :type: BotPartialList
        """
        if new_bots is None:
            raise ValueError("Invalid value for `new_bots`, must not be `None`")  # noqa: E501

        self._new_bots = new_bots

    @property
    def features(self):
        """Gets the features of this BotIndex.  # noqa: E501


        :return: The features of this BotIndex.  # noqa: E501
        :rtype: BotFeatures
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this BotIndex.


        :param features: The features of this BotIndex.  # noqa: E501
        :type: BotFeatures
        """

        self._features = features

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BotIndex, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BotIndex):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
